// <auto-generated />
namespace TSI.GymTech.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_New_Student_Views : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_New_Student_Views));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061516514_Create_New_Student_Views"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
