// <auto-generated />
namespace TSI.GymTech.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_TrainingSheetView_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_TrainingSheetView_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201909200044586_Add_TrainingSheetView_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
