//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSI.GymTech.Entity.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrainingSheetExercise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrainingSheetExercise() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSI.GymTech.Entity.App_LocalResources.TrainingSheetExercise", typeof(TrainingSheetExercise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise is required..
        /// </summary>
        public static string ExerciseRequired {
            get {
                return ResourceManager.GetString("ExerciseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Repetitions.
        /// </summary>
        public static string NumberOfRepetitions {
            get {
                return ResourceManager.GetString("NumberOfRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Repetitions is required..
        /// </summary>
        public static string NumberOfRepetitionsRequired {
            get {
                return ResourceManager.GetString("NumberOfRepetitionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie is required..
        /// </summary>
        public static string SerieRequired {
            get {
                return ResourceManager.GetString("SerieRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Sheet Exercise ID.
        /// </summary>
        public static string TrainingSheetExerciseId {
            get {
                return ResourceManager.GetString("TrainingSheetExerciseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Sheet Exercise ID is required..
        /// </summary>
        public static string TrainingSheetExerciseIdRequired {
            get {
                return ResourceManager.GetString("TrainingSheetExerciseIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Sheet is required..
        /// </summary>
        public static string TrainingSheetRequired {
            get {
                return ResourceManager.GetString("TrainingSheetRequired", resourceCulture);
            }
        }
    }
}
